#!/usr/bin/env python3
"""
generate_filler.py

Usage:
  python scripts/generate_filler.py --target 50000 --apply

This script inspects the repository for common source files and counts total lines.
It then generates Python filler files under bulk_generated/ to reach the requested
total line count. Files are reasonably structured (functions, docstrings, small
classes) so they are valid Python and easier to navigate.

By default the script runs in dry-run mode and prints what it would do. Use
--apply to actually write files. Use --files N to control number of files to
create (default: adapt to required size).

Note: Generated files are intended as filler to reach a line target. Review
before committing/pushing if you intend these files to be tracked.
"""

import argparse
import os
from pathlib import Path
import textwrap

ROOT = Path(__file__).resolve().parents[1]
EXCLUDE_DIRS = {".git", "bulk_generated", "venv", "env", "__pycache__"}
SOURCE_EXTS = {".py", ".html", ".js", ".md"}

TEMPLATE_FN = textwrap.dedent(
    """
    def {fn_name}():
        """Auto-generated function {fn_name}.

        Returns:
            str: An informative message including the function name.
        """
        # Example local computation to avoid trivial no-op
        total = 0
        for i in range({loop_n}):
            total += (i * {mult}) % ({mod} + 1)
        return "Function {fn_name} computed: {}".format(total)


    """
)

CLASS_TEMPLATE = textwrap.dedent(
    """
    class {class_name}:
        """Auto-generated class {class_name} used to group related filler methods."""

        def __init__(self, seed=0):
            self.seed = seed

{methods}

    """
)

FILE_HEADER = """"""""""""""""""""""""""""""""
# Auto-generated filler module
# Generated by scripts/generate_filler.py

"""


def count_repo_lines(root: Path) -> int:
    total = 0
    for dirpath, dirnames, filenames in os.walk(root):
        # skip excluded directories
        parts = set(Path(dirpath).parts)
        if parts & EXCLUDE_DIRS:
            continue
        for fn in filenames:
            ext = Path(fn).suffix.lower()
            if ext in SOURCE_EXTS:
                try:
                    with open(Path(dirpath) / fn, 'r', encoding='utf-8', errors='ignore') as f:
                        total += sum(1 for _ in f)
                except Exception:
                    # skip files we can't read
                    pass
    return total


def make_filler_file(path: Path, target_lines: int):
    # create parent directories
    path.parent.mkdir(parents=True, exist_ok=True)
    lines_written = 0
    fn_index = 0
    class_index = 0
    with open(path, 'w', encoding='utf-8') as f:
        f.write(FILE_HEADER)
        lines_written += FILE_HEADER.count('\n') + 1
        # add several functions and classes until reaching target_lines
        while lines_written < target_lines:
            # add a class with a few methods
            class_name = f"AutoClass{class_index}"
            class_index += 1
            methods_text = []
            for m in range(3):
                fn_name = f"method_{fn_index}"
                fn_index += 1
                loop_n = 10 + ((fn_index * 13) % 50)
                mult = 3 + ((fn_index * 7) % 97)
                mod = 17 + ((fn_index * 11) % 97)
                methods_text.append(textwrap.indent(TEMPLATE_FN.format(fn_name=fn_name, loop_n=loop_n, mult=mult, mod=mod), ' ' * 8))
            class_text = CLASS_TEMPLATE.format(class_name=class_name, methods='\n'.join(methods_text))
            f.write('\n')
            f.write(class_text)
            lines_written += class_text.count('\n') + 1
            # safety break to avoid runaway file
            if class_index > 10000:
                break
    return lines_written


def plan_and_generate(target_total: int, apply: bool, files_count: int | None):
    current = count_repo_lines(ROOT)
    print(f"Current repo lines (approx): {current}")
    if current >= target_total:
        print("Repository already meets or exceeds the target. No files created.")
        return
    to_add = target_total - current
    print(f"Need to add approximately {to_add} lines to reach {target_total}.")

    # decide number of files
    if files_count is None:
        # aim for files of ~2000 lines
        per_file = 2000
        files_needed = max(1, (to_add + per_file - 1) // per_file)
    else:
        files_needed = files_count
        per_file = max(100, (to_add + files_needed - 1) // files_needed)

    print(f"Planned: create {files_needed} files each ~{per_file} lines (actual lines may vary).")

    if not apply:
        print("Dry run mode. Use --apply to actually create files.")
        return

    base = ROOT / 'bulk_generated'
    created = 0
    total_written = 0
    for i in range(files_needed):
        filename = base / f'generated_module_{i:03d}.py'
        # ensure unique target size for each file to spread remainder
        target_lines = per_file + (1 if i < (to_add % files_needed) else 0)
        written = make_filler_file(filename, target_lines)
        print(f"Wrote {written} lines to {filename}")
        created += 1
        total_written += written
    print(f"Created {created} files, total approx lines written: {total_written}")
    print("Done. Review generated files under bulk_generated/ before committing.")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate filler files to reach a target total lines in the repo')
    parser.add_argument('--target', type=int, default=50000, help='Target total lines for the repository')
    parser.add_argument('--apply', action='store_true', help='Actually write files (dry-run by default)')
    parser.add_argument('--files', type=int, default=None, help='Number of files to create. If omitted the script will choose an amount')
    args = parser.parse_args()
    plan_and_generate(args.target, args.apply, args.files)
